### ISSUE TITLE
Load and save the region of memory.

### ISSUE THREAD

**Issue by xolod79** [hoglet67/AtomBusMon#10]
There is a suggestion, add commands for load and save the region of memory through the transmission of a binary stream in the terminal program.  e.g. Realterm.

**Comment by obiwanjacobi** [comment]
That is an excellent idea.
Even better, if you can take control of the entire CPU bus, you can write software that can perform hardware tests in the system you're connected to.
[2c]

**Comment by hoglet67** [comment]
The current firmware includes an srec command that allows data in srecord format to be uploaded.

To download data, there is currently just the mem command, but I'm thinking of adding an srecord output command (#11)

Granted neither of these are binary, but they already exist.

In terms of scripting remote tests, the rdm, wrm, rdi and wri commands could be used to read/write memory space / IO space.

One thing that is missing is the ability to force the CPU to start executing at a given location (#12).

**Comment by hoglet67** [comment]
Fixed in dev branch (firmware version 0.97)

**Comment by xolod79** [comment]
Excellent! Thank you.
