### ISSUE TITLE
New firmware version for GODIL500

### ISSUE THREAD

**Issue by xolod79** [hoglet67/AtomBusMon#16]
Please, build a new version firmware for GODIL500.

I restored my Godil after burnout of one pin due to improper insertion into the connector.  replacement of the 74CB3T16211 buffer fixed the problem.

**Comment by hoglet67** [comment]
I've just done a complete rebuild of all targets, and uploaded a new release here:
https://github.com/hoglet67/AtomBusMon/releases/tag/release_2

That includes 4 builds for the GODIL500:
```
   780476  2019-12-15 17:20   ice_20191215_1612_0981/godil_500/ice6809/ice6809.mcs
   780476  2019-12-15 17:20   ice_20191215_1612_0981/godil_500/icez80/icez80.mcs
   780476  2019-12-15 17:20   ice_20191215_1612_0981/godil_500/ice6502/ice6502.mcs
   780476  2019-12-15 17:20   ice_20191215_1612_0981/godil_500/ice65c02/ice65c02.mcs
```
Please let me know if you encounter any problems.

Dave

**Comment by xolod79** [comment]
Thank you.
