### ISSUE TITLE
Mask RESET with 'special' command?

### ISSUE THREAD

**Issue by jessaskey** [hoglet67/AtomBusMon#22]
In several hardware configurations, either the 6502,6809 or Z-80 are a slave processor. In those situations it is common that if the CPU stops responding to the master CPU, that the Master CPU will reset the slave to try and get it back on track. When doing commands like 'test' or even just interrupting the processor on the ICE, it will force a reset to happen.

I was wondering if it was possible to mask the RESET signal into the CPU core so that it is possible to debug via ICE and ignore any RESETs sent via the input pin? This would be similar to the masking if the IRQ and NMI (and FIRQ on 6809) inputs but would expand to the RESET. I looked at the code and it looks like there may be a 0x7 limit on the mask definitions which would make this more difficult on the 6809?

**Comment by hoglet67** [comment]
Masking of the control inputs (including reset) is greatly improved in the latest version.

There is now a set of four "x" commands, one per control input.

These replace the rather confusing "special" command.

On the 6502 they are:
```
   xirq      e|c|d|f
   xnmi      e|c|d|f
   xres      e|c|d|f
   xso       e|c|d|f
```
(On the Z80 and 6809 versions they are renamed appropriately)

The commands take four possible options:
- e = Enabled (the default state - connected to the external signal)
- c = Conditionally enabled (connected to the external signal only when free-running)
- d = Disconnected (connected to a logic 1)
- f = Forced (connected to a logic 0)

**Comment by jessaskey** [comment]
Thank you... this is great... I will get my units reprogrammed this week to test out.. appreciate it!
