### ISSUE TITLE
PCB for the (Z80) adapter board

### ISSUE THREAD

**Issue by scott8** [hoglet67/AtomBusMon#24]
Dave,
I'd like a PCB for the (Z80) adapter board. Do you still have these? 

Thanks,
Scott

**Comment by hoglet67** [comment]
Looking at my spreadsheet, I should have 3 boards left.

Where abouts in the world are you?

Do you already have the FPGA board? I don't believe these are available at the moment.

**Comment by scott8** [comment]
David,
I think the new alias ***@***.***" is not working.
If you'll email me directly at ***@***.***, I'll show you what I
found.
I don't want to put the location out on the github web site so I'd like you
to email me privately.

Thanks,
Scott
m: 602-309-8216

**Comment by scott8** [comment]
Will this board work?

Features:

- Spartan 6 XC6SLX9 FPGA
- UART Port
- RS485 PORT
- 1 LED to show when the FPGA is correctly configured
- On board voltage regulation that can handle 5V
- 8PCS Programmed LEDS
- 4PCS Programmed Keys
- On board flash memory M25P16 to store the FPGA configuration file.

[image: xc6slx9.jpg]

**Comment by hoglet67** [comment]
You email address above has been obfuscated.

I also don't see the attached imaged, but the description matches this board:
https://www.aliexpress.com/item/32887046050.html

Sorry no, that won't work, because the connector pinouts are different.

**Comment by scott8** [comment]
That's the one. What's it take to make that work? It appears to be the only
game in town.

**Comment by hoglet67** [comment]
The adapter PCB board would need to be redesigned to match the form factor/connector pinout, and then the FPGA pinout (the .UCF file) would likely need to be updated as well. It's alot of work, and by that time there are no guarantees the FPGA board will still be available.

It's a mugs game at this point! I'm not doing any more work on this project until the situation stabllises.

**Comment by scott8** [comment]
This one?

https://www.amazon.com/Developement-Spartan-6-Spartan3-Spartan-3e-XC3S250E/dp/B08MT36M2Z

**Comment by scott8** [comment]
Any others:
https://www.google.com/search?q=Xilinx%20%20FPGA%20Spartan%206%20%20XC6SLX9%20Core%20Board

?

**Comment by hoglet67** [comment]
I don't mean to be dismissive, but there is just not enough information to tell.

You need to get hold of:
- mechanical drawings that show the exact connector spacing
- schematics, that show the locations of the power supply pins on the connectors

To be honest, it's very unlikely that you'll find an exact match to the eepizza board, unless someone has literally cloned the design (which I don't think has happened).

This issue here is that the FPGA in pretty much unobtainable at the moment. Anyone who has stocks is selling the FPGA alone for ~$100. Once the FPGA becomes available again, then it's likely that the eepizza board will become available.

Have you reached out to eepizza? Depending on how much you are wiling to pay, he may be able to source parts to make a small number of boards.

**Comment by hoglet67** [comment]
My only other suggestion is to make a wanted post on the stardot forum. I know several folk there bought this board and are possibly not using it. Again, depending on you much you are prepared to pay, someone may be willing to move theirs on.

**Comment by scott8** [comment]
Thanks. I understand.
I have 6 of these:
XILINX
XC9536
VQG44AM1049
F4336248A
10C

I don't know if they are the right chip. I emailed the maker of the GODIL
board to find out.

I will get on the forum and put up a wanted post as you suggested.

Thanks,
Scott

**Comment by hoglet67** [comment]
No, they are not the right chip.

Those are small Xilinx CPLDs.

The FPGA on the eepizza is an XC6SLX9-2TQG144C

The GODIL is irrelvant to this, that was an even older version of the ICE.

**Comment by scott8** [comment]
Please send me your email address.
I have something to send you that I think you're going to want to see,
regarding the public domain CP/M license.

Thanks,
Scott

**Comment by hoglet67** [comment]
Sorry, I try not to share my email address...

If you want me to see it, then you can post it here, or on stardot.

**Comment by scott8** [comment]
No problem.

See the attached PDF.
Post this far and wide.

Happy Trails,
Scott

**Comment by hoglet67** [comment]
I think you possibly forgot to attach the PDF.

**Comment by scott8** [comment]
No. It apparently won't go through.
That's why I wanted your email address.

Scott

**Comment by scott8** [comment]
Here you go. It's been posted.

http://www.cpm.z80.de/license.html

Scott

**Comment by scott8** [comment]
I have access to one a few.
I need to discuss details with you.
Please email me at ***@***.*** so we can discuss this offline.

Thanks,
Scott

**Comment by hoglet67** [comment]
Scott,

It's not economic for me to post boards to the US.

This project is open source, and the gerbers for the Z80 board are linked to here:
https://github.com/hoglet67/AtomBusMon/wiki/Z80-CPU-Adapter

It would be cheaper for you to order a batch of 5 boards directly from JLCPCB.

regards

Dave
