### ISSUE TITLE
Fill command, fill in one byte more than necessary

### ISSUE THREAD

**Issue by xolod79** [hoglet67/AtomBusMon#5]
Fill command, fill in one byte more than necessary
On Z80 
>> fill 4000 40ff ff
but 4100 filling too

**Comment by hoglet67** [comment]
I've just checked the code, and I can't see the error:
```
void doCmdFill(char *params) {
  long i;
  unsigned int start;
  unsigned int end;
  unsigned int data;
  sscanf(params, "%x %x %x", &start, &end, &data);
  log0("Wr: %04X to %04X = %02X\n", start, end, data);
  loadData(data);
  loadAddr(start);
  for (i = start; i <= end; i++) {
    writeMemByteInc();
  }
}
```
Can you attach a log the demonstrates this happening please?

**Comment by xolod79** [comment]
unsigned int data;
Maybe the data should be a byte and not 16bit word?

**Comment by hoglet67** [comment]
Please can you attach a log, and I'll look into this.

**Comment by xolod79** [comment]
It seems that the problems with my Godil50 board, I solder it by swapping the connectors up and was sloppy.
Installed it in the ZX-Spectrum (Pentagon 128), partially launches but hangs. launched a memory test.
test 8000 ffff
produces a lot of errors with some sort of bit address relationship.
[capture.zip](https://github.com/hoglet67/AtomBusMon/files/3202240/capture.zip)

**Comment by xolod79** [comment]
iI apologize. The problem was in the zx-spectrum board (Pentagon 128). I plan to put the buffer(74ALS245) on the data bus. I think it should work with him.

**Comment by hoglet67** [comment]
Thanks for letting me know.
